### ISSUE TITLE
Question about Event Marker Latency between Unity and Emotiv

### ISSUE THREAD

**Issue by gomsing** [xfleckx/LSL4Unity#59]
I'm currently using Emotiv (EEG) and Unity for my experiment, but there is a consistent latency in the recorded markers. 

I verified the marker time with EpochTime and it turns out that the EEG data with the inlet marker stream (sent from Unity) is consistent (with understandable latency of a few milliseconds)

However, according to the LSL timestamps (it was recorded with LabRecorder), the two markers have a disparity of about .200 point of labrecorder time. 

When I plot it out, I think the difference is about 200ms. 

I'm stumped in why this would happen as the markers are aligned in the EEG inlet with Epochtime, and it is the same datastream recorded in Unity. I don't know why there is so much difference in LabRecorder time and Epochtime. Can you help me narrow down the issue? Thank you

![image](https://github.com/labstreaminglayer/LSL4Unity/assets/64123849/915fa354-1eac-41b4-8ba5-25e37189b46c)

![image](https://github.com/labstreaminglayer/LSL4Unity/assets/64123849/06196eae-18cc-4f62-b71f-8a8d0013e786)

**Comment by cboulay** [comment]
What is "EpochTime"?

Are you recording in Unity?

**Comment by gomsing** [comment]
@cboulay 

EpochTime is the Unix time, the number of seconds that have elapsed since January 1, 1970 (midnight UTC/GMT)

The recording is done on LabRecorder, and the streams are a) the marker stream sent from Unity (outlet) b) the EEG stream sent from Emotiv (outlet) with the inlet marker data from Unity. The Unity outlet is both received by the LabRecorder and Emotiv. However, the timing of the same data point is different on LabRecorder timestamp (I'm guessing it is the LSL internal clock), whileas it is same on the Unix timestamp that was recorded with the data point.

**Comment by cboulay** [comment]
LSL doesn't use Unix time. It uses std::chrono::steady_clock. That might be Unix time on some systems but that's only a coincidence and we don't rely on that.

When you push the LSL sample from Unity, are you providing the timestamp or just letting it auto-timestamp?
When you load the xdf file, are you letting it do clock correction (should be enabled by default)?

And I have no idea what Emotiv is doing on their end. If they are adding custom timestamps to their streams then they are using LSL incorrectly.

**Comment by gomsing** [comment]
@cboulay 

The Unix time was just added for the EEG inlet for timing accuracy (the EEG recorder uses Unix time), so it was just recorded as another data point. The problem was that the data that should have been recorded approximately at the same time (the same timestamp from Unity outlet -> LabRecorder, and the same timestamp from Unity outlet -> EEG inlet -> EEG+Unity data to outlet -> LabRecorder) does not match on the LSL clock, but it does on the Unix timepoint that was recorded at the same time with the marker. 

When I push sample from Unity, I just let it auto-timestamp in LSL, but also record the Unix time, too, as it was recommended by Emotiv for EEG timing accuracy. 

When I load the XDF file, I just take the record data as it is, and did not do any correction on my part. So if it was enabled by default, the data I got should have been corrected. 

I'm quite stuck as the time interval between markers is almost the same on both clocks (LSL clock and Unix clock) but the time point that the marker is recorded is vastly different. 

My speculation is that there is a latency in the Emotiv outlet process, and the timestamp of the Unix time is not the real-time timing but just the timestamp value A that was kept in the system, then pushed to LSL at timepoint B (B-A being the latency in LSL time).

**Comment by cboulay** [comment]
My guess is that the Emotiv software is using something like `outlet.push_chunk(chunk, time=epoch_time())`. If that's the case then the data is unrecoverable. They need to switch to using `outlet.push_chunk(chunk, time=lsl::local_clock())` or no timestamp at all because that's the default: https://github.com/sccn/liblsl/blob/master/include/lsl_cpp.h#L535

If they want to provide a custom timestamp because they know there's some latency between the EEG acquisition and the time it's available in the software then they need to convert their custom timestamp to use the same timebase as std::chrono::steady_clock.

**Comment by gomsing** [comment]
@cboulay 

I plotted out the signals and I think it is the problem on the Emotiv software.

![image](https://github.com/labstreaminglayer/LSL4Unity/assets/64123849/7e5c3ac1-3239-4507-b7a5-4dfa48519808)

I will resolve this issue with them, thank you for your insights.

**Comment by cboulay** [comment]
I still don't understand your setup. My guess that the Emotiv software is incorrectly providing custom timestamps is based entirely on your table in your first post that says the LSL timestamps are e+6 whereas the other timestamps are e+9, clearly using different time bases.

What is the Emotiv software doing with your events anyway? It's taking in LSL events and then adding them to the EEG stream then re-streaming that out? Is that just one EEG stream with an added channel for markers?

If that's what they are doing then the Emotiv software also needs to enable postprocessing on the event inlet so it will convert the timestamp associated with the event from the origin PC's clock to the Emotiv app PC's clock, because they will be re-streaming the events as though they are coming from the Emotiv PC and thus they need to use the Emotiv PC's clock for those events' timestamps.

https://github.com/sccn/liblsl/blob/master/include/lsl_cpp.h#L997-L1011

**Comment by gomsing** [comment]
My guess that the Emotiv software is incorrectly providing custom timestamps is based entirely on your table in your first post that says the LSL timestamps are e+6 whereas the other timestamps are e+9, clearly using different time bases.
>> You are correct, according to Emotiv they use Unix time for their time bases. 

What is the Emotiv software doing with your events anyway? It's taking in LSL events and then adding them to the EEG stream then re-streaming that out? Is that just one EEG stream with an added channel for markers?
>> You are correct! It takes in LSL events and added another channel in the EEG stream with the Marker values. These are the data headers of each data stream recorded in LabRecorder. 
EEG :  ['Timestamp', 'Counter', 'Interpolate', 'Cz', 'Fz', 'Fp1', 'F7', 'F3', 'FC1', 'C3', 'FC5', 'FT9', 'T7', 'CP5', 'CP1', 'P3', 'P7', 'PO9', 'O1', 'Pz', 'Oz', 'O2', 'PO10', 'P8', 'P4', 'CP2', 'CP6', 'T8', 'FT10', 'FC6', 'C4', 'FC2', 'F4', 'F8', 'Fp2', 'HardwareMarker', 'Markers']
Marker :  ['MarkerTime', 'MarkerValue', 'CurrentTime']

I added the 'MarkerTime (Unix time)' in my Unity LSL stream on Emotiv's instructions bc they said that the event markers will be aligned with the EEG stream according to that timestamp

**Comment by cboulay** [comment]
That's very annoying of them.

You'll have to hack the xdf importer to only apply clock sync correction to the non-Emotiv streams.
Then, for your Unity stream, you can use the MarkerTime (Unix time) and the corrected timestamp to create a vector of x,y pairs that relate the Unix time to LSL time. You can then do a linear regression on this to create a model that maps between the two time bases. Finally, convert your LSL times to Unix time, or vice versa.

BTW, it's dangerous to rely on Unix time being synchronized across computers and this is the main reason LSL doesn't use it. If LSL used Unix time (instead of steady_clock) then people would assume the time was meaningful and reliable, but it is not.
Just today I was helping a team of developers who were doing some synchronization testing with Unix time between a mobile device and a desktop. For one developer, they were pretty similar. For another, the mobile device clock was ahead by about 1 second. For another, the desktop clock was ahead by 9 seconds.
Unix time is not something you can rely on to synchronize different PCs at msec time scales (unless those PCs are explicitly synchronized with eachother using something like hardware PTP and you know the clock uses the PTP time -- then you can get <microsec synchronization!).

**Comment by gomsing** [comment]
@cboulay 

The experiment I am doing right now is based on the same computer, which is why I'm more stumped on why there would be a data inconsistency even on the same computer clock. But my lab mates are trying to sync multiple devices, so I will tell them. Thank you. 

I will look into solving the clock sync correction. Thank you for your help.
